# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webnewsapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://webnewsacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ea46252a4bb1407e8bd009330542bb7e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c2d0fe34381b4db98fa1e8b87886200d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: webnewsacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ea46252a4bb1407e8bd009330542bb7e }}/webnewsapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webnewsapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a0191fdcce8e47128aa109b5321c6d02 }}
        images: 'webnewsacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ea46252a4bb1407e8bd009330542bb7e }}/webnewsapi:${{ github.sha }}'